setup_dir = "/data/data6/vijay/sparsity_capsule/results/epi/baseline/3d_mtlsd"
voxel_size = [ 235, 75, 75,]
max_iterations = 20000
save_checkpoints_every = 5000
save_snapshots_every = 5000
[[samples]]
raw = "/data/data6/vijay/sparsity_capsule/data/epi/volume_2.zarr/raw"
labels = "/data/data6/vijay/sparsity_capsule/data/epi/volume_2.zarr/labels"

