out_result_dir = "/data/data6/vijay/sparsity_capsule/results/epi/baseline/epi.zarr/3d_mtlsd/20000"
out_result = "/data/data6/vijay/sparsity_capsule/results/epi/baseline/epi.zarr/3d_mtlsd/20000/results_gt_epi.json"
seg_datasets_prefix = "/data/data6/vijay/sparsity_capsule/results/epi/baseline/epi.zarr/3d_mtlsd/20000/segmentations_mws"

[gt]
labels_dataset = "/data/data6/vijay/sparsity_capsule/data/epi/volume_1.zarr/labels"
