affs_dataset = "/data/data6/vijay/sparsity_capsule/results/prism/pgt/prism.zarr/3Af2A/25000--from--2d_mtlsd_20000/3d_affs"
fragments_dataset = "/data/data6/vijay/sparsity_capsule/results/prism/pgt/prism.zarr/3Af2A/25000--from--2d_mtlsd_20000/fragments_mws"
seg_dataset_prefix = "/data/data6/vijay/sparsity_capsule/results/prism/pgt/prism.zarr/3Af2A/25000--from--2d_mtlsd_20000/segmentations_mws"
blockwise = false
num_workers = 1

fill_holes = true
[mws_params]
aff_neighborhood = [ [ -1, 0, 0,], [ 0, -1, 0,], [ 0, 0, -1,], [ -2, 0, 0,], [ 0, -9, 0,], [ 0, 0, -9,], [ -3, 0, 0,], [ 0, -27, 0,], [ 0, 0, -27,],]
bias = [ -0.3, -0.3, -0.3, -0.7, -0.7, -0.7, -0.7, -0.7, -0.7,]
noise_eps = 0.001
strides = [ [ 1, 1, 1,], [ 1, 1, 1,], [ 1, 1, 1,], [ 1, 2, 2,], [ 1, 2, 2,], [ 1, 2, 2,], [ 2, 5, 5,], [ 2, 5, 5,], [ 2, 5, 5,],]
randomized_strides = true
filter_fragments = 0.1
remove_debris = 100
seed_eps = 0.01
