setup_dir = "/data/data6/vijay/sparsity_capsule/results/epi/pgt/2d_mtlsd"
voxel_size = [ 235, 75, 75,]
max_iterations = 40000
save_checkpoints_every = 5000
save_snapshots_every = 5000
[[samples]]
raw = "/data/data6/vijay/sparsity_capsule/data/epi/volume_1.zarr/raw"
labels = "/data/data6/vijay/sparsity_capsule/data/epi/volume_1.zarr/sparse_labels"
mask = "/data/data6/vijay/sparsity_capsule/data/epi/volume_1.zarr/sparse_labels_mask"
