out_result_dir = "/data/data6/vijay/sparsity_capsule/results/cremi_c/baseline/cremi_c.zarr/3d_mtlsd/30000"
out_result = "/data/data6/vijay/sparsity_capsule/results/cremi_c/baseline/cremi_c.zarr/3d_mtlsd/30000/results_gt_cremi_c.json"
seg_datasets_prefix = "/data/data6/vijay/sparsity_capsule/results/cremi_c/baseline/cremi_c.zarr/3d_mtlsd/30000/segmentations_mws"

[gt]
labels_dataset = "/data/data6/vijay/sparsity_capsule/data/cremi_c/volume_1.zarr/labels"
