out_result_dir = "/data/data6/vijay/sparsity_capsule/results/liconn/pgt/liconn.zarr/3Af2M/25000--from--2d_mtlsd_20000"
out_result = "/data/data6/vijay/sparsity_capsule/results/liconn/pgt/liconn.zarr/3Af2M/25000--from--2d_mtlsd_20000/results_gt_liconn.json"
seg_datasets_prefix = "/data/data6/vijay/sparsity_capsule/results/liconn/pgt/liconn.zarr/3Af2M/25000--from--2d_mtlsd_20000/segmentations_mws"

[gt]
labels_dataset = "/data/data6/vijay/sparsity_capsule/data/liconn/volume_1.zarr/labels"
